{{- if eq .Values.config.registryType "ocp" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "registry-scanner.fullname" .}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-viewer
subjects:
- kind: ServiceAccount
  name: {{ include "registry-scanner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
