{{- if or .Values.daemonset.deploy .Values.delegatedAgentDeployment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.configmapName" . }}
  namespace: {{ include "agent.namespace" . }}
  labels:
{{ (include "agent.labels" .) | indent 4 }}
data:
  dragent.yaml: |
{{ include "agent.configMap" . | fromYaml | toYaml | indent 4 }}
{{- if .Values.prometheus.file }}
  prometheus.yaml: |
{{ toYaml .Values.prometheus.yaml | indent 4 }}
{{- end }}
{{- end }}
